[workspace]
resolver = "2"
members = ["examples/dioxus-native-in-bevy", "examples/bevy-in-dioxus-native"]

[workspace.package]
version = "0.7.5"

# dependencies that are shared across packages
[workspace.dependencies]
wgpu = { version = "29.0.3" }

bevy = { git = "https://github.com/bevyengine/bevy", rev = "2002a188e0e106eacf56b854dfaff4eca8839584" }

dioxus = { version = "0.7.8", default-features = false }
dioxus-asset-resolver = { version = "0.7.8" }
dioxus-devtools = { version = "0.7.8" }

blitz-dom = { git = "https://github.com/dioxuslabs/blitz", rev = "01b602382de766d77d1c372a689d407a2a64a4d4", default-features = false }
blitz-paint = { git = "https://github.com/dioxuslabs/blitz", rev = "01b602382de766d77d1c372a689d407a2a64a4d4" }
blitz-traits = { git = "https://github.com/dioxuslabs/blitz", rev = "01b602382de766d77d1c372a689d407a2a64a4d4" }
dioxus-native = { git = "https://github.com/dioxuslabs/blitz", rev = "01b602382de766d77d1c372a689d407a2a64a4d4" }
dioxus-native-dom = { git = "https://github.com/dioxuslabs/blitz", rev = "01b602382de766d77d1c372a689d407a2a64a4d4" }
data-url = "0.3.2"

anyrender = { git = "https://github.com/dioxuslabs/anyrender", rev = "6b19c229c147b8143eb649bffb868fc323e956fe", default-features = false }
anyrender_vello = { git = "https://github.com/dioxuslabs/anyrender", rev = "6b19c229c147b8143eb649bffb868fc323e956fe", default-features = false }
vello = { git = "https://github.com/linebender/vello", rev = "7023c3f03deff7100d2fc2e361959a439f14a3b7", default-features = false }

color = "0.3.2"
peniko = "0.6.0"
tracing-subscriber = { version = "0.3.20", default-features = false }
bytes = "1.10.1"
async-std = "1.13.1"
crossbeam-channel = "0.5"
paste = "1.0.12"
rustc-hash = "2.1.1"

[patch.crates-io]
kurbo = { git = "https://github.com/linebender/kurbo", rev = "6836244" }